CREATE SEQUENCE tb_categories_SEQ           START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE tb_comments_SEQ             START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE tb_projects_SEQ             START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE tb_tickets_SEQ              START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE tb_users_SEQ                START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE tb_workflow_transitions_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE tb_workflows_SEQ            START WITH 1 INCREMENT BY 1;

CREATE TABLE tb_users (
    id               BIGINT NOT NULL,
    email            VARCHAR(255) NOT NULL,
    encoded_password VARCHAR(255) NOT NULL,
    name             VARCHAR(255) NOT NULL,
    roles            VARCHAR(255) ARRAY,

    CONSTRAINT tb_users_PK PRIMARY KEY (id),
    CONSTRAINT tb_users_UK UNIQUE(email)
);

CREATE TABLE tb_categories (
    id    BIGINT NOT NULL,
    color VARCHAR(255),
    name  VARCHAR(255),

    CONSTRAINT tb_categories_PK PRIMARY KEY (id),
    CONSTRAINT tb_categories_UK UNIQUE(name)
);

CREATE TABLE tb_workflow_status (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,

    CONSTRAINT tb_workflow_status_PK PRIMARY KEY (id),
    CONSTRAINT tb_workflow_status_UK UNIQUE (name)
);

CREATE TABLE tb_workflows (
    id       BIGINT NOT NULL,
    name     VARCHAR(255),
    start_id BIGINT NOT NULL,

    CONSTRAINT tb_workflows_PK PRIMARY KEY (id),
    CONSTRAINT tb_workflows_UK UNIQUE (name),
    CONSTRAINT tb_workflows_start_FK FOREIGN KEY (start_id) REFERENCES tb_workflow_status
);

CREATE TABLE tb_projects (
    id          BIGINT NOT NULL,
    description TEXT,
    name        VARCHAR(255) NOT NULL,
    workflow_id BIGINT NOT NULL,

    CONSTRAINT tb_project_PK PRIMARY KEY (id),
    CONSTRAINT tb_project_UK UNIQUE (name),
    CONSTRAINT tb_project_workflow_FK FOREIGN KEY (workflow_id) REFERENCES tb_workflows
);

CREATE TABLE tb_tickets (
    id          BIGINT NOT NULL,
    title       VARCHAR(255),
    description TEXT,
    created_at  TIMESTAMP(6) WITH TIME ZONE,
    deleted     BOOLEAN DEFAULT false,
    updated_at  TIMESTAMP(6) WITH TIME ZONE,
    assignee_id BIGINT,
    author_id   BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    project_id  BIGINT,
    status_id   BIGINT NOT NULL,

    CONSTRAINT tb_tickets_PK PRIMARY KEY (id),
    CONSTRAINT tb_tickets_assignee_FK FOREIGN KEY (assignee_id) REFERENCES tb_users,
    CONSTRAINT tb_tickets_author_FK   FOREIGN KEY (author_id)   REFERENCES tb_users,
    CONSTRAINT tb_tickets_category_FK FOREIGN KEY (category_id) REFERENCES tb_categories,
    CONSTRAINT tb_tickets_project_FK  FOREIGN KEY (project_id)  REFERENCES tb_projects,
    CONSTRAINT tb_tickets_status_FK   FOREIGN KEY (status_id)   REFERENCES tb_workflow_status
);

CREATE TABLE tb_comments (
    id         BIGINT NOT NULL,
    content    TEXT,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    author_id  BIGINT,
    ticket_id  BIGINT NOT NULL,

    CONSTRAINT tb_comments_PK PRIMARY KEY (id),
    CONSTRAINT tb_comment_user_FK   FOREIGN KEY (author_id) REFERENCES tb_users,
    CONSTRAINT tb_comment_ticket_FK FOREIGN KEY (ticket_id) REFERENCES tb_tickets
);

CREATE TABLE tb_ticket_history (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    description VARCHAR(255) NOT NULL,
    timestamp   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    ticket_id   BIGINT NOT NULL,
    user_id     BIGINT NOT NULL,

    CONSTRAINT tb_ticket_history_PK PRIMARY KEY (id),
    CONSTRAINT tb_ticket_history_ticket_FK FOREIGN KEY (ticket_id) REFERENCES tb_tickets,
    CONSTRAINT tb_ticket_history_user_FK   FOREIGN KEY (user_id)   REFERENCES tb_users

);

CREATE TABLE tb_workflow_statuses (
    workflow_id BIGINT NOT NULL,
    status_id   BIGINT NOT NULL,

    CONSTRAINT tb_workflow_statuses_status_FK   FOREIGN KEY (status_id)   REFERENCES tb_workflow_status,
    CONSTRAINT tb_workflow_statuses_workflow_FK FOREIGN KEY (workflow_id) REFERENCES tb_workflows
);

CREATE TABLE tb_workflow_transitions (
    id          BIGINT NOT NULL,
    from_id     BIGINT NOT NULL,
    to_id       BIGINT NOT NULL,
    workflow_id BIGINT,

    CONSTRAINT tb_workflow_transitions_PK PRIMARY KEY (id),
    CONSTRAINT tb_workflow_transition_UK  UNIQUE (workflow_id, from_id, to_id),
    CONSTRAINT tb_workflow_transition_from_FK     FOREIGN KEY (from_id)     REFERENCES tb_workflow_status,
    CONSTRAINT tb_workflow_transition_to_FK       FOREIGN KEY (to_id)       REFERENCES tb_workflow_status,
    CONSTRAINT tb_workflow_transition_workflow_FK FOREIGN KEY (workflow_id) REFERENCES tb_workflows
);