CREATE TABLE tb_users (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username         VARCHAR(15) NOT NULL,
    name             VARCHAR(255) NOT NULL,
    email            VARCHAR(255) NOT NULL,
    encoded_password VARCHAR(255) NOT NULL,
    roles            VARCHAR(255) ARRAY,
    deleted     BOOLEAN DEFAULT false,

    CONSTRAINT tb_users_email_UK    UNIQUE(email),
    CONSTRAINT tb_users_username_UK UNIQUE(username)
);

CREATE TABLE tb_categories (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(64) NOT NULL,
    color VARCHAR(16),

    CONSTRAINT tb_categories_UK UNIQUE(name)
);

CREATE TABLE tb_workflow_status (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,

    CONSTRAINT tb_workflow_status_UK UNIQUE (name)
);

CREATE TABLE tb_workflows (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255),
    start_id BIGINT NOT NULL,

    CONSTRAINT tb_workflows_UK UNIQUE (name),
    CONSTRAINT tb_workflows_start_FK FOREIGN KEY (start_id) REFERENCES tb_workflow_status
);

CREATE TABLE tb_projects (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(64) NOT NULL,
    description TEXT,
    prefix      VARCHAR(15) NOT NULL,
    workflow_id BIGINT NOT NULL,

    CONSTRAINT tb_project_UK UNIQUE (name),
    CONSTRAINT tb_project_workflow_FK FOREIGN KEY (workflow_id) REFERENCES tb_workflows
);

CREATE TABLE tb_tickets (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identifier  VARCHAR(25) NOT NULL,
    title       VARCHAR(255),
    description TEXT,
    created_at  TIMESTAMP(6) WITH TIME ZONE,
    updated_at  TIMESTAMP(6) WITH TIME ZONE,
    assignee_id BIGINT,
    author_id   BIGINT NOT NULL,
    project_id  BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    status_id   BIGINT NOT NULL,
    deleted     BOOLEAN DEFAULT false,

    CONSTRAINT tb_project_ID_UK       UNIQUE (identifier),
    CONSTRAINT tb_tickets_assignee_FK FOREIGN KEY (assignee_id) REFERENCES tb_users,
    CONSTRAINT tb_tickets_author_FK   FOREIGN KEY (author_id)   REFERENCES tb_users,
    CONSTRAINT tb_tickets_category_FK FOREIGN KEY (category_id) REFERENCES tb_categories,
    CONSTRAINT tb_tickets_project_FK  FOREIGN KEY (project_id)  REFERENCES tb_projects,
    CONSTRAINT tb_tickets_status_FK   FOREIGN KEY (status_id)   REFERENCES tb_workflow_status
);

CREATE TABLE tb_tickets_subscribers (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id       BIGINT NOT NULL,
    subscriber_id   BIGINT NOT NULL,

    CONSTRAINT tb_tickets_subscribers_ticket_FK     FOREIGN KEY (ticket_id)     REFERENCES tb_tickets,
    CONSTRAINT tb_tickets_subscribers_subscriber_FK FOREIGN KEY (subscriber_id) REFERENCES tb_users
);

CREATE TABLE tb_comments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content    TEXT,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    author_id  BIGINT,
    ticket_id  BIGINT NOT NULL,

    CONSTRAINT tb_comment_user_FK   FOREIGN KEY (author_id) REFERENCES tb_users,
    CONSTRAINT tb_comment_ticket_FK FOREIGN KEY (ticket_id) REFERENCES tb_tickets
);

CREATE TABLE tb_ticket_history (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    description VARCHAR(255) NOT NULL,
    timestamp   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    ticket_id   BIGINT NOT NULL,
    user_id     BIGINT NOT NULL,

    CONSTRAINT tb_ticket_history_ticket_FK FOREIGN KEY (ticket_id) REFERENCES tb_tickets,
    CONSTRAINT tb_ticket_history_user_FK   FOREIGN KEY (user_id)   REFERENCES tb_users

);

CREATE TABLE tb_workflow_statuses (
    workflow_id BIGINT NOT NULL,
    status_id   BIGINT NOT NULL,

    CONSTRAINT tb_workflow_statuses_status_FK   FOREIGN KEY (status_id)   REFERENCES tb_workflow_status,
    CONSTRAINT tb_workflow_statuses_workflow_FK FOREIGN KEY (workflow_id) REFERENCES tb_workflows
);

CREATE TABLE tb_workflow_transitions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_id     BIGINT NOT NULL,
    to_id       BIGINT NOT NULL,
    workflow_id BIGINT,

    CONSTRAINT tb_workflow_transition_UK  UNIQUE (workflow_id, from_id, to_id),
    CONSTRAINT tb_workflow_transition_from_FK     FOREIGN KEY (from_id)     REFERENCES tb_workflow_status,
    CONSTRAINT tb_workflow_transition_to_FK       FOREIGN KEY (to_id)       REFERENCES tb_workflow_status,
    CONSTRAINT tb_workflow_transition_workflow_FK FOREIGN KEY (workflow_id) REFERENCES tb_workflows
);

CREATE TABLE tb_notifications (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type        VARCHAR(56) NOT NULL,
    receive_id  BIGINT NOT NULL,
    reffer_id   BIGINT NOT NULL,
    read        BOOLEAN DEFAULT false,
    content     VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE,

    CONSTRAINT tb_notifications_receive_FK FOREIGN KEY (receive_id) REFERENCES tb_users,
    CONSTRAINT tb_notifications_reffer_FK  FOREIGN KEY (reffer_id)  REFERENCES tb_tickets
);

-- Usuário com apenas a role ADMIN
INSERT INTO tb_users (username, name, email, encoded_password, roles) VALUES ('admin', 'System Administrator', 'sysadmin@morpho-board.ui', 'IwS3Mm4oGEfpwPDC3Vom20ViYgXhVCxHeBGr8aluY9tC9o668ghxJ2fMQQUwq+7GWJkzX1HguXOtdwVkblUzTw==', '{ADMIN}');